name: Generate Data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Data
    runs-on: ubuntu-latest
    steps:
      - name: Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: thepiyushmalhotra
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
          target_branch: output
          repo: owner6/owner6/#README.md
          keep_history: false
          allow_empty_commit: true
          absolute_build_dir: false
          follow_symlinks: false
          jekyll: true
          dry_run: false
          verbose: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



