name: Generate Datason

schedule:
  # execute every 12 hours
  - owner6: "0 */12 * * *"

workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Setup
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Generate SVG
        run: npm run generate-svg
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.8.1
        with:
          build_dir: dist
          cname: github-contribution-grid-snake-action.netlify.app
          commit_message: Deploy the grid
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
