name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_DAYS_OF_WEEK: "false"  # Отключает статистику по дням недели
          SHOW_TIME_RANGE: "all_time"      # Показывает статистику за все время
