name: Waka Readme

on:
  schedule:
    # Запускается каждый день в 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_COMMIT: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          SHOW_PROJECTS: "true"
